name: NDGeneration
version: 1.0.0
author: DevCyntrix
description: 'Disables the diamond ore generation in the Minecraft worlds.'
website: 'https://github.com/DevCyntrix/NoDiamondGeneration'

main: de.devcyntrix.ndg.NDGPlugin